//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class merch
    {
        public int id { get; set; }
        public byte[] photo { get; set; }
        public string name { get; set; }
        public string dexcription { get; set; }
        public string manufacturer { get; set; }
        public int price { get; set; }
        public Nullable<int> discount { get; set; }
    }
}
